### ISSUE TITLE
Include bug fixes for topology errors in ehv level 

### ISSUE THREAD

**Issue by IlkaCu** [openego/data_processing#207]
Bug fixes documented in [this issue](https://github.com/openego/osmTGmod/issues/10) need to be included in the upcoming dp run.

**Comment by IlkaCu** [comment]
Further manual adjustments need to be checked and included in the dp: [eTraGo#97](https://github.com/openego/eTraGo/issues/97) and [eTraGo#96](https://github.com/openego/eTraGo/issues/96)

**Comment by ClaraBuettner** [comment]
I took a closer look to the problems explained in eTraGo#97 and eTraGo#96. I couldn't find a reason for the USW Marke (eTraGo#97). But the lines need to be connected right to the USW, so I would add this bug fix to the existing script that fixes subnetworks. No buses are added or deleted, so it shouldn't cause problems. 
The lines close to Jessen (eTraGo#96) which are missing in our data have been added in december 2016, regarding the Issue, we use osm-data from october 2016. The lines should be added when updating osm-data. I'm not sure if this should be fixed manually, there will be more new lines in osm ad it would be somehow inconsistent to add only those. 
What do you think?

**Comment by IlkaCu** [comment]
As we won't include a new osm import in open_eGo I think you can simply add the missing lines to our data model. Please note in a comment within the code that these additions may be obsolete when using a new osm import.

**Comment by ClaraBuettner** [comment]
Ok, to add the lines to Jessen I need new 110kV buses and split up one existing line. New 110kV buses seemed to be a problem when I fixed the last topological errors. Otherwise I can't connect the new line to the existing one. Is it still a problem to add them?

**Comment by nesnoj** [comment]
(note: u might use stuff from my adjustments here: https://github.com/openego/eTraGo/issues/96#issuecomment-363046533)

**Comment by ClaraBuettner** [comment]
I added the changes to fix the problems in Marke and near Jessen in the existing file in dp-branch  feature/fix_eHV_subnetworks. Basically it's the same nesnoj already did, but I changed the way lines and buses are referenced.

**Comment by IlkaCu** [comment]
Could you create a pull request and assign nesnoj an me?

**Comment by ClaraBuettner** [comment]
I implemented it as a sort of postprocessing in the utilities of the dataprocessing. But I remember that you wanted to integrate it earlier. When you tell me where it should be, I move it there and create a pull request by then.

**Comment by IlkaCu** [comment]
You can include it in the powerflow part of the dataprocessing - right behind the script 'ego_dp_powerflow_lopf_data.sql'.

**Comment by ClaraBuettner** [comment]
Then I still need to reconnect generators and loads. I thought I should integrate it earlier to avoid this.

**Comment by IlkaCu** [comment]
Right! Then we should include it after the 'ego_dp_powerflow_grid_future_scenarios.sql' - script, right?

**Comment by IlkaCu** [comment]
It seems that the adjustments for 'Umspannwerk Marke' did not work properly. In the current data set in the model_draft (v0.4.1)  we see two subgrids around here. One consisting of bus 17124, 17477 and line 20258. The other subgrid is an isolated bus with bus_id= 17939.
Furthermore the connecting line between the 110 kV lines east of 'UW Marke' and the substation itself is still missing. 
@ClaraBuettner: Can you help and check the code for bugs? 

![grafik](https://user-images.githubusercontent.com/16799094/41527410-58550b08-72e7-11e8-8606-7d4dc0fadac8.png)

**Comment by ClaraBuettner** [comment]
I changed some buses from lines without changing the geom, so its not that easy to see what I did there. I think the subnetworks are not needed anymore and can be deleted. 
When I calculate, I don't get any subnetworks but my data looks the same. 
I'll take a closer look on this soon.

**Comment by IlkaCu** [comment]
The current data version in the model_draft definitely includes the mentioned subnetworks. Additionally there is no line added to connect the 110 kV lines on the right with the substation itself, which was the initial incentive to adjust the grid topology around 'UW Marke'. See https://github.com/openego/eTraGo/issues/97

**Comment by IlkaCu** [comment]
> I changed some buses from lines without changing the geom, so its not that easy to see what I did there.

Now I understand what you mean. I think it would be good to change the geom of the lines as well. Otherwise it looks like a topology error when looking at the data in QGIS.

**Comment by ClaraBuettner** [comment]
Yes, I know this wasn't that good, but I guess the problem needed to be fixed soon, so I didn't focused on that. 
I have to write exams next week, but I try to implement this as soon as possible.

**Comment by ClaraBuettner** [comment]
I just updated the geom of the lines with updated buses, but the straight connection (green) looks much different than the real one (orange). Is this ok when I leave the length and x' as it was or should I try to update the real geom in order to have a better result? I know the second option is better but it needs much more time... 
![marke](https://user-images.githubusercontent.com/22964326/41647763-721ffe94-7477-11e8-98a3-054a0d91fdca.png)

**Comment by IlkaCu** [comment]
For now this looks fine for me. We can discuss whether we want to implement a more sophisticated approach after your exams. 
From my point of view it's the most important to implement the Delete-statements to get rid of the subnetworks.

**Comment by IlkaCu** [comment]
The mentioned bugfixes are implemented in the current version of the data set.
