### ISSUE TITLE
replace the ego_scenario_log with a multiproject scenario_log

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#226]
The **ego_scenario_log** will be used in other oedb projects (open_FRED, SzenarienDB) as well. 
Since it is not a good idea to make simple copies of the log table and the log function I will change the system to a multiproject scenario log.

- [x] Create new **scenario_log** table
- [x] Migrate **ego_scenario_log** to new table
- [x] Create new function
- [x] Deactivate old function (leave a message)
- [x] Adapt all scripts of ego
- [x] Expect different bugs and be ready to solve them

**Comment by Ludee** [comment]
```SQL
INSERT INTO model_draft.scenario_log (project,version,io,schema_name,table_name,script_name,entries,comment,user_name,timestamp,meta_data)
SELECT 'eGo_DP',version,io,schema_name,table_name,script_name,entries,status,user_name,timestamp,meta_data
FROM model_draft.ego_scenario_log
ORDER BY id;
```

**Comment by IlkaCu** [comment]
@gplssm @Ludee The function write_ego_scenario_log for python scripts is not yet adjusted to the multiproject scenario log. 
This causes a bug in the DP when executing ego_dp_powerflow_griddistrict_demand.py.
Please provide a bugfix.

**Comment by Ludee** [comment]
In progress. Should be fixed before noon!

**Comment by IlkaCu** [comment]
@Ludee: Is there any news?

**Comment by gplssm** [comment]
> @Ludee: Is there any news?

I'm about to test it... I'll report back soon

**Comment by gplssm** [comment]
Am I doing something wrong or is it simply not working...?

```
[truncated]

sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "model_draft.ego_scenario_log" does not exist
LINE 1: INSERT INTO model_draft.ego_scenario_log (project, version, ...
                    ^
 [SQL: 'INSERT INTO model_draft.ego_scenario_log (project, version, io, schema_name, table_name, script_name, entries, status, user_name, timestamp, meta_data) VALUES (%(project)s, %(version)s, %(io)s, %(schema_name)s, %(table_name)s, %(script_name)s, %(entries)s, %(status)s, %(user_name)s, %(timestamp)s, %(meta_data)s) RETURNING model_draft.ego_scenario_log.id'] [parameters: {'project': 'testthisshit', 'version': 'v0.3.0', 'io': 'output', 'schema_name': 'model_draft', 'table_name': 'ego_demand_loadarea_peak_load', 'script_name': 'peak_load_per_load_area.py', 'entries': 1, 'status': None, 'user_name': 'unknown', 'timestamp': datetime.datetime(2018, 5, 31, 16, 19, 51, 110159), 'meta_data': None}] (Background on this error at: http://sqlalche.me/e/f405
```

**Comment by gplssm** [comment]
I adated the test command

```
python3 -c "from egoio.tools import db; from dataprocessing.python_scripts.functions.ego_scenario_log import write_scenario_log; conn = db.connection(section='oedb'); write_scenario_log(conn=conn, project='testthisshit',version='v0.3.0', io='output', schema='model_draft', table='ego_demand_loadarea_peak_load', script='peak_load_per_load_area.py', entries=1)"
```

Still doesn't work, here' the traceback (truncated)
```
  File "/home/guido/virtualenvs/data_processing/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/guido/virtualenvs/data_processing/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/guido/virtualenvs/data_processing/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/guido/virtualenvs/data_processing/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/guido/virtualenvs/data_processing/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/guido/virtualenvs/data_processing/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/guido/virtualenvs/data_processing/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/guido/virtualenvs/data_processing/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/guido/virtualenvs/data_processing/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "status" of relation "scenario_log" does not exist
LINE 1: ...o, schema_name, table_name, script_name, entries, status, us...
                                                             ^
 [SQL: 'INSERT INTO model_draft.scenario_log (project, version, io, schema_name, table_name, script_name, entries, status, user_name, timestamp, meta_data) VALUES (%(project)s, %(version)s, %(io)s, %(schema_name)s, %(table_name)s, %(script_name)s, %(entries)s, %(status)s, %(user_name)s, %(timestamp)s, %(meta_data)s) RETURNING model_draft.scenario_log.id'] [parameters: {'project': 'testthisshit', 'version': 'v0.3.0', 'io': 'output', 'schema_name': 'model_draft', 'table_name': 'ego_demand_loadarea_peak_load', 'script_name': 'peak_load_per_load_area.py', 'entries': 1, 'status': None, 'user_name': 'unknown', 'timestamp': datetime.datetime(2018, 5, 31, 16, 51, 2, 788523), 'meta_data': None}] (Background on this error at: http://sqlalche.me/e/f405
```

**Comment by jh-RLI** [comment]
@IlkaCu Test was successful, you have to pull the repo "egoio" also because i changed some things there too

**Comment by IlkaCu** [comment]
I still receive the following error message: 
```
2018-05-31 09:02:42 Execute 'ego_dp_powerflow_griddistrict_demand.py' ...
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/openego/data_processing/dataprocessing/eGo_data_processing.py in <module>()
    157 
    158 if __name__ == '__main__':
--> 159     data_processing()

/home/openego/data_processing/dataprocessing/eGo_data_processing.py in data_processing()
    139 
    140             # execute desired sql snippet
--> 141             exec(compile(script_str, filename, 'exec'), globals())
    142         else:
    143             raise NameError('{} is neither a python nor a sql script (at least it '

/home/openego/data_processing/dataprocessing/python_scripts/ego_dp_powerflow_griddistrict_demand.py in <module>()
     22 from math import sqrt
     23 from dataprocessing.tools import io, metadata
---> 24 from dataprocessing.python_scripts.functions.ego_scenario_log import write_ego_scenario_log
     25 
     26 

ImportError: cannot import name 'write_ego_scenario_log'
```

I pulled the egoio and I'm on the dev branch there. Any ideas?

**Comment by IlkaCu** [comment]
Of course - you renamed the function...

**Comment by IlkaCu** [comment]
I adjusted the Python script in the DP accordingly and the script finished successfully. Thanks for your help.
