### ISSUE TITLE
Run peak_load.py

### ISSUE THREAD

**Issue by Ludee** [openego/data_processing#44]
I want to run **peak_load_per_load_area.py** from @gplssm and @IlkaCu on my anaconda.
Therefore I need to install/update packages:

I installed the current ego.io (version='0.0.2') successfully. 
When installing dataprocessing the version is not accepted. see [setup.py](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/setup.py#L21)

**Comment by ulfmueller** [comment]
Does it help if you checkout to a previous version of ego.io (as a quick workaround)?

**Comment by Ludee** [comment]
I just "allowed" the new version. Not sure if legal?

**Comment by ulfmueller** [comment]
if it works it should be fine! any objections @nesnoj @gplssm ?

**Comment by nesnoj** [comment]
That should be ok for now. As soon as we release dp v0.2 a new version of ego.io is to be released as well and the setup.py of dp has to be adjusted anyway to meet the new version.

**Comment by nesnoj** [comment]
@Ludee, you mentioned that the peak load table doesn't exist. I fixed the table name in ego.io (https://github.com/openego/ego.io/commit/35ba97957270dd3b7ab6e9c9e7585056cace1f6d), plz give it another try. Make sure u r in refactor branch in ego.io.
This is a temp solution, as soon as the new table defs are generated (https://github.com/openego/ego.io/issues/8) this kind of errors will hopefully be a thing of the past..

**Comment by Ludee** [comment]
Running script: "L:\github\openego\data_processing\dataprocessing\eGo_data_processing.py"
2017-02-08 11:17:01 ego data processing started...
ego data processing started...
2017-02-08 11:17:05 Execute 'peak_load_per_load_area.py' ...
Execute 'peak_load_per_load_area.py' ...
Traceback (most recent call last):
  File "L:\github\openego\data_processing\dataprocessing\eGo_data_processing.py", line 114, in <module>
    data_processing()
  File "L:\github\openego\data_processing\dataprocessing\eGo_data_processing.py", line 96, in data_processing
    exec(compile(script_str, filename, 'exec'))
  File "L:\github\openego\data_processing\dataprocessing\python_scripts\peak_load_per_load_area.py", line 213, in <module>
    tools.grant_db_access(conn, schema, target_table, db_group)
  File "C:\Anaconda3\envs\lupy35\lib\site-packages\oemof\db\tools.py", line 350, in grant_db_access
    conn.execute(grant_str)
  File "C:\Anaconda3\envs\lupy35\lib\site-packages\sqlalchemy\engine\base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "C:\Anaconda3\envs\lupy35\lib\site-packages\sqlalchemy\engine\base.py", line 1097, in _execute_text
    statement, parameters
  File "C:\Anaconda3\envs\lupy35\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "C:\Anaconda3\envs\lupy35\lib\site-packages\sqlalchemy\engine\base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "C:\Anaconda3\envs\lupy35\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Anaconda3\envs\lupy35\lib\site-packages\sqlalchemy\util\compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "C:\Anaconda3\envs\lupy35\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Anaconda3\envs\lupy35\lib\site-packages\sqlalchemy\engine\default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "model_draft.ego_demand_loadarea_peak_load" does not exist
 [SQL: 'GRANT ALL ON TABLE model_draft.ego_demand_loadarea_peak_load\n    TO oeuser WITH GRANT OPTION;']

**Comment by nesnoj** [comment]
I'm on it...

**Comment by nesnoj** [comment]
Couldn't reproduce your error - table is created and grants are set correctly.
Currently running the whole script...
If there won't be any drawbacks, I'll add it to data_proc to facilitate automation.

**Comment by Ludee** [comment]
The peak loads are still missing the scenario log. 
I also made a python def, where do I put it? In ego.io?

**Comment by nesnoj** [comment]
The [current version in dev](https://github.com/openego/data_processing/blob/a2126af5b624fcda73bf2e3e0332634e8d3831f8/dataprocessing/python_scripts/peak_load_per_load_area.py) is the one which I'm running.. so feel free to embed into data_proc main script and add scenario log :).

> I also made a python def, where do I put it? In ego.io?

If u mean the table def in ego.io, this was [automatically done](https://github.com/openego/ego.io/issues/8#issuecomment-278921367) just now by @MGlauer (see [here](https://github.com/openego/ego.io/blob/e96c23cc36ff5cf527ea6c46e2083a01fc57a3a1/egoio/db_tables/model_draft.py#L571))

**Comment by nesnoj** [comment]
I haven't updated the import statement according to these new defs but we have to update all dp scripts anyway. I propose that we gonna do this in one go..

**Comment by Ludee** [comment]
I think I mean something else. The [scenario_log function](https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/functions/function_ego_scenario_log.sql) (SQL) just adds one entry to the log table. This is only implemented in the SQL snippets. We need to extend it to the python files as well.

I'm not sure if this is the right way, but it works:

> 
> def ego_scenario_log(con,version,io,schema,table,script,comment):
>     """
>     write entry in scenario log table
>     Parameters
>     ----------
>     con : SQLAlchemy connection object
>     version: str
>         Version number
>     io: str
>         IO-type (input, output, temp)
>     schema : str
>         Database schema
>     table : str
>         Database table
>     script : str
>         Script name
>     comment : str
>         Comment
> 
>     Returns
>     -------
>     None
>     """
>     sql=text("""
>     INSERT INTO model_draft.ego_scenario_log
>         (version,io,schema_name,table_name,script_name,entries,comment,
>         user_name,timestamp,metadata)
>     SELECT	'{0}' AS version,
>             '{1}' AS io,
>             '{2}' AS schema_name,
>             '{3}' AS table_name,
>             '{4}' AS script_name,
>             COUNT(*)AS entries,
>             '{5}' AS status,
>             session_user AS user_name,
>             NOW() AT TIME ZONE 'Europe/Berlin' AS timestamp,
>             obj_description('{2}.{3}' ::regclass) ::json AS metadata
>     FROM	{2}.{3};""".format(version,io,schema,table,script,comment))
>     con.execute(sql)

> ego_scenario_log(con,version,'import','model_draft','some_table','script.py','metastring')

**Comment by nesnoj** [comment]
Thank you for the proposal. I altered your function using python ORM (latest ego.io branch) and created a new **python script for adding entries to scenario log** (423e7c1b3b8f055780cfa7f11fe362e0899740a0). It might be helpful @IlkaCu @wolfbunke @lukasol @ulfmueller @gplssm.

It was not possible to adapt all columns in python - I extracted the user name from the current DB connection but things like number of entries must be passed to the function.
As an example I added calls of the new script to the peak load scripts in ae93806accdccf5b21024d9f8ac60b9c9771f835.

@IlkaCu: What about the [`demand_per_mv_grid_district.py`](https://github.com/openego/data_processing/blob/ae93806accdccf5b21024d9f8ac60b9c9771f835/dataprocessing/python_scripts/demand_per_mv_grid_district.py) - is this still in use?

**General note:** It might be good to move the functions (sql and py subdirs) to the more general tools (similar discussion regarding db access [here](https://github.com/openego/ego.io/issues/16)). I propose to put in on schedule for v0.3.

**Comment by IlkaCu** [comment]
> @IlkaCu: What about the demand_per_mv_grid_district.py - is this still in use?

As far as I know this is still part of the data processing. As @gplssm is the author, he is the one in charge here.

**Comment by nesnoj** [comment]
Ok, I thought this is part of your aggregation.

@gplssm: So this question goes to you..
If it is still needed we have to update the tables according to new ego.io defs and integrate logging.

**Comment by gplssm** [comment]
I would hope that it is still in use ;-) Bring demand time series for transition point, respectively per mv grid district.

What do I have to do?

**Comment by nesnoj** [comment]
Nice to read you! But don't worry about it..
I'm a little curious about the function of the different demand/load/.. scripts (the headers often lack required info), this makes it difficult to update the mentioned script.  As far as I can see from the [BPMN](https://github.com/openego/data_processing/blob/2766d1967e31eef1edfa218c9dedfdb3bdd4c87f/bpmn/ego_data_processing.graphml), the renaming has to be:

- `ego_deu_consumption.calc_ego_loads` => `model_draft.ego_demand_loadarea`
In v0.1 the table held consumption only, this is now contained in loadara, right?
- `calc_ego_loads.ego_demand_per_transition_point` => `model_draft.ego_demand_hvmv_demand` (used [here](https://github.com/openego/data_processing/blob/2766d1967e31eef1edfa218c9dedfdb3bdd4c87f/dataprocessing/sql_snippets/demandseries_TOPF.sql)) There's no ego.io def, I [inserted manually](https://github.com/openego/ego.io/commit/40d97c8091b53d549ee968f002dc0bf6ec457236).

Hope I got this [right](https://github.com/openego/data_processing/commit/911ea5a36aa3e9f4849bfb0b3a35450f34f76dce), currently running..

There some discrepancies in coding style using orm and pd's real_sql but I didn't fix it - who cares :)
